CRUDMVC/Models/BasicInformation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}

CRUDMVC/Controllers/BasicInformationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRUDMVC.Models;

namespace CRUDMVC.Controllers
{
    public class BasicInformationsController : Controller
    {
        private EmployeeEntities db = new EmployeeEntities();

        // GET: BasicInformations
        public ActionResult Index()
        {
            return View(db.BasicInformations.ToList());
        }

        // GET: BasicInformations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BasicInformation basicInformation = db.BasicInformations.Find(id);
            if (basicInformation == null)
            {
                return HttpNotFound();
            }
            return View(basicInformation);
        }

        // GET: BasicInformations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BasicInformations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,CreatedAt,UpdatedAt")] BasicInformation basicInformation)
        {
            if (ModelState.IsValid)
            {
                var name = basicInformation.Name;
                var count = db.BasicInformations.Where(s => s.Name.Contains(name)).Count();
                if (count > 0)
                {
                    ViewBag.message = "Name already exists";
                    return View();
                }
                basicInformation.CreatedAt = DateTime.Now;
                basicInformation.UpdatedAt = DateTime.Now;
                db.BasicInformations.Add(basicInformation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.message = "Insert failed!";
            return View();
        }

        // GET: BasicInformations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BasicInformation basicInformation = db.BasicInformations.Find(id);
            if (basicInformation == null)
            {
                return HttpNotFound();
            }
            return View(basicInformation);
        }

        // POST: BasicInformations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,CreatedAt,UpdatedAt")] BasicInformation basicInformation)
        {
            if (ModelState.IsValid)
            {
                var data = db.BasicInformations.Find(basicInformation.Id);

                data.Name = basicInformation.Name;
                data.Address = basicInformation.Address;
                data.UpdatedAt = DateTime.Now;
                db.Entry(data).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var dataEdit = db.BasicInformations.Where(s => s.Id == basicInformation.Id).FirstOrDefault();
            return View(dataEdit);
        }

        // GET: BasicInformations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BasicInformation basicInformation = db.BasicInformations.Find(id);
            if (basicInformation == null)
            {
                return HttpNotFound();
            }
            return View(basicInformation);
        }

        // POST: BasicInformations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BasicInformation basicInformation = db.BasicInformations.Find(id);
            db.BasicInformations.Remove(basicInformation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRUDMVC/Views/BasicInformations/Create.cshtml
@model CRUDMVC.Models.BasicInformation

@{
    ViewBag.Title = "Add Basic Information";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container" style="border:1px solid">
        <div class="row">

            <div class="col-sm-12">

                <div style="border-bottom: 1px solid;padding: 12px;background-color: aliceblue;">
                    Add Basic Information
                </div>

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <label>Name</label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Name" })
                    </div>

                    <div class="form-group">
                        <label>Address</label>
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control", @placeholder = "Address" })
                    </div>

                    <div class="form-group">
                        <input type="submit" name="submit" value="Create" class="btn btn-success" />
                        <a href="@Url.Action("Index", "BasicInformations")" class="btn btn-default">Back to List</a>
                        @if (ViewBag.message != "")
                        {
                        <span style="color:red">@ViewBag.message</span>
                        }
                    </div>

                </div>
            </div>

        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CRUDMVC/Views/BasicInformations/Delete.cshtml
@model CRUDMVC.Models.BasicInformation

@{
    ViewBag.Title = "Delete Basic Information";
}

<h4 style="color:red">Are you sure you want to delete this?</h4>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="container" style="border:1px solid">
        <div class="row">

            <div class="col-sm-12">

                <div style="border-bottom: 1px solid;padding: 12px;background-color: aliceblue;">
                    Delete Basic Information
                </div>

                <div class="box-body">

                    <div class="form-group">
                        <label>Name</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
                    </div>

                    <div class="form-group">
                        <label>Address</label>
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        @Html.ActionLink("Back to List", "Index", "BasicInformations", new { @class = "btn btn-default" })
                    </div>

                </div>
            </div>
        </div>
    </div>
}

CRUDMVC/Views/BasicInformations/Details.cshtml
@model CRUDMVC.Models.BasicInformation

@{
    ViewBag.Title = "Details Basic Information";
}

<div class="container" style="border:1px solid">
    <div class="row">

        <div class="col-sm-12">

            <div style="border-bottom: 1px solid;padding: 12px;background-color: aliceblue;">
                Details Basic Information
            </div>

            <div class="box-body">                              
                <div class="form-group">
                    <label>Name</label>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })                   
                </div>

                <div class="form-group">
                    <label>Address</label>
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })                 
                </div>

                <div class="form-group">
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-success"})
                    @Html.ActionLink("Back to List", "Index", "BasicInformations", new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
</div>

CRUDMVC/Views/BasicInformations/Edit.cshtml
@model CRUDMVC.Models.BasicInformation

@{
    ViewBag.Title = "Edit Basic Information";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="container" style="border:1px solid">
        <div class="row">

            <div class="col-sm-12">

                <div style="border-bottom: 1px solid;padding: 12px;background-color: aliceblue;">
                    Edit Basic Information
                </div>

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        <label>Name</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Address</label>
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <input type="submit" name="submit" value="Update" class="btn btn-success" />
                        <a href="@Url.Action("Index", "BasicInformations")" class="btn btn-default">Back to List</a>
                        @if (ViewBag.message != "")
                        {
                            <span style="color:red">@ViewBag.message</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CRUDMVC/Views/BasicInformations/Index.cshtml
@model IEnumerable<CRUDMVC.Models.BasicInformation>

@{
    ViewBag.Title = "List Basic Information";
}
<h2>List Basic Information</h2>
<p>
    <a href="@Url.Action("Create", "BasicInformations")" class="btn btn-success">Create New</a>
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>